In [20]:
import torch
import torch.nn as nn 
import torch.distributions as td

In [21]:
norm = td.Normal(nn.Parameter(torch.ones(1)), nn.Parameter(1e-10 * torch.ones(1)))
norm2 = td.Normal(torch.ones(1), 1e-10 * torch.ones(1))

In [ ]:
norm.sample([2])
norm.prob

tensor([[1.],
        [1.]])

In [23]:
norm.rsample([2])

tensor([[1.],
        [1.]], grad_fn=<AddBackward0>)

In [24]:
norm2.sample([2])

tensor([[1.],
        [1.]])

In [27]:
norm2.rsample([2])

tensor([[1.],
        [1.]])